<a href="https://colab.research.google.com/github/clionelove123/Machine_Learning/blob/main/ML_Chap_09_Jacobian_Hessian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def Jacobian(x):
    return np.array([x[0], 0.4*x[1], 1.2*x[2]])

def Hessian(x):
    #return array([[.2,0],[0,1]])
    return np.array([[1,0,0],[0,0.4,0],[0,0,1.2]])

In [ ]:
def steepest(x0):

    i = 0
    iMax = 10
    x = x0
    Delta = 1
    alpha = 1

    while i < iMax and Delta > 10**(-5):
        p = -Jacobian(x)
        xOld = x
        x = x + alpha * p
        Delta = np.sum((x - xOld)**2)
        print(x)
        i += 1

In [ ]:
def Newton(x0):

    i = 0
    iMax = 10
    x = x0
    Delta = 1
    alpha = 1

    while i<iMax and Delta>10**(-5):
        p = -np.dot(np.linalg.inv(Hessian(x)),Jacobian(x))
        xOld = x
        x = x + alpha*p
        Delta = np.sum((x-xOld)**2)
        i += 1
    print (x)

In [ ]:
x0 = np.array([-2, 2, -2])

steepest(x0)

[0.  1.2 0.4]
[ 0.    0.72 -0.08]
[0.    0.432 0.016]
[ 0.      0.2592 -0.0032]
[0.      0.15552 0.00064]
[ 0.        0.093312 -0.000128]
[0.00000e+00 5.59872e-02 2.56000e-05]
[ 0.000000e+00  3.359232e-02 -5.120000e-06]
[0.0000000e+00 2.0155392e-02 1.0240000e-06]
[ 0.00000000e+00  1.20932352e-02 -2.04800000e-07]


In [ ]:
x0 = np.array([-2, 2, -2])

Newton(x0)

[0. 0. 0.]
