<a href="https://colab.research.google.com/github/clionelove123/Machine_Learning/blob/main/ML_Chap_05_RBF_Network_textbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import rbf
import pylab as pl

In [5]:
iris = np.loadtxt('/content/iris_proc.data',delimiter=',')

In [6]:
iris[:,:4] = iris[:,:4]-iris[:,:4].mean(axis=0)
imax = np.concatenate((iris.max(axis=0)*np.ones((1,5)),iris.min(axis=0)*np.ones((1,5))),axis=0).max(axis=0)
iris[:,:4] = iris[:,:4]/imax[:4]
#print iris[0:5,:]

#target = zeros((shape(iris)[0],2));
#indices = where(iris[:,4]==0)
#target[indices,0] = 1
#indices = where(iris[:,4]==1)
#target[indices,1] = 1
#indices = where(iris[:,4]==2)
#target[indices,0] = 1
#target[indices,1] = 1

target = np.zeros((np.shape(iris)[0],3));
indices = np.where(iris[:,4]==0)
target[indices,0] = 1
indices = np.where(iris[:,4]==1)
target[indices,1] = 1
indices = np.where(iris[:,4]==2)
target[indices,2] = 1


order = range(np.shape(iris)[0])
np.random.shuffle([150,4])
iris = iris[order,:]
target = target[order,:]

train = iris[::2,0:4]
traint = target[::2]
valid = iris[1::4,0:4]
validt = target[1::4]
test = iris[3::4,0:4]
testt = target[3::4]

#print train.max(axis=0), train.min(axis=0)

net = rbf.rbf(train,traint,5,1,1)

net.rbftrain(train,traint,0.25,2000)
#net.confmat(train,traint)
net.confmat(test,testt)

[[12.  0.  0.]
 [ 0. 12.  0.]
 [ 0.  1. 12.]]
0.972972972972973
